version: "3"
services:
  python-cgi:
    restart: unless-stopped
    container_name: python-cgi
    build: ./apache-python-image
    ports:
      - "8181:80"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
      - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./cgi-bin:/usr/local/apache2/cgi-bin

